### ISSUE TITLE
support remove menu item and add separator in submenu

### ISSUE THREAD

**Issue by xiaozhuai** [getlantern/systray#150]
1. Can't add separator in submenu
2. Can't remove a exists menu item, not just hide

**Comment by davidnewhall** [comment]
+1 I have a situation where I really need to be able to close the channels on my menus. They are created dynamically, and once in a while a reload occurs that may totally change them. Since I run this on multiple platforms, and I cannot exit systray in macOS, being able to delete menus entirely would be an ideal ability.
