### ISSUE TITLE
libayatana support?

### ISSUE THREAD

**Issue by nekr0z** [getlantern/systray#191]
It looks like Debian [is deprecating libappindicator](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037) in favour of `libayatana-appindicator`. Any chance it will be supported by `systray`?

**Comment by shellhazard** [comment]
Is there a workaround for this? Haven't been able to satisfy the dependency on Debian Bullseye.

**Comment by ppacher** [comment]
Any update on this?

**Comment by nekr0z** [comment]
I ended up making [a fork](https://github.com/nekr0z/systray). The diff is just a couple of lines.

I'd make a pull request but I can't figure out choosing which dependency to use on the library level. It is, however, fairly trivial to use build tags to have your app compiled to use [the original library](https://github.com/nekr0z/matebook-applet/blob/master/systray_legacy.go) or [the forked one](https://github.com/nekr0z/matebook-applet/blob/master/systray.go).

**Comment by Crosse** [comment]
I've proposed #225 to allow this library to build against both the older `libappindicator` and new `libayatana-appindicator` libraries.

**Comment by Crosse** [comment]
Closed via #225.

**Comment by dhaavi** [comment]
For anyone further looking into this: This ended up being a bad idea for our use case, as we ship a single binary for multiple distros. From what we can tell, this then broke all the systrays on everything not based on Debian, as all others don't have the `libayatana-appindicator` library.

Our solution was to switch to the fork https://github.com/fyne-io/systray, as they now use dbus directly instead of a C lib.

Maybe this is a change you might want to consider upstreaming.

**Comment by Crosse** [comment]
Interesting. Once I’m back “in the office” I’ll take a look at that and see if we can do the same or similar. Thanks for the heads-up.
