### ISSUE TITLE
Example or info how to run Systray as a service in Windows

### ISSUE THREAD

**Issue by niels-s** [getlantern/systray#21]
Hi there,

I'm looking around to see if I can find a solution to run my go binary as a service in windows. I've tried a couple things already:

1) I've tried using this go lib to setup a service but unfortunately this won't work nicely together with Systray since we need to start the ui in main: github.com/kardianos/service
2) Another approach I've tried is [NSSM](https://nssm.cc/). While is was able to register a simple dummy go app printing a message every 5 seconds. NSSM doesn't play nice with Systray.

I'm hoping some of you can share you experiences on how you run you app's as a service on Windows in combination with Systray.

Thanks!

**Comment by myleshorton** [comment]
hey @niels-s -- in my experience windows services in general are a bit of a nightmare -- super cumbersome and error prone. If you want something to just run at startup, all you need is a registry setting. That's what lantern does.

**Comment by niels-s** [comment]
@myleshorton thanks for the info! If I may ask one final question, could you help me a bit and point me in the right direction where I could find the windows installer code for Lantern?

**Comment by phoenix147** [comment]
Since i came around the same problem, i just wanted to add, that it is technically impossible to show a system tray for processes running as service in windows. You have to write a second indicator application, that runs with user privileges, and somehow communicates with the service.

Mysql for example does this with its Notifier program.
