### ISSUE TITLE
MacOS set SUID permissions There will be problems

### ISSUE THREAD

**Issue by PBK-B** [getlantern/systray#248]
Use the [example](https://github.com/getlantern/systray/tree/master/example) code to reproduce.
The reproduction steps are as follows
```
git clone git@github.com:getlantern/systray.git
cd example

go build 
sudo chmod +s ./example
./example
```
The error message is as follows
```
xxx:core root$ ./example 
2023-01-28 18:05:16.137 example[38764:379629] The application with bundle ID (null) is running setugid(), which is not allowed. Exiting.
```
<img width="845" alt="fix this" src="https://user-images.githubusercontent.com/39079814/215261406-1da21eaf-c5fb-4fb4-96cc-9910800e5ab8.png">

I think my application needs this permissions, if any suggestions or ideas can help me

**Comment by renard** [comment]
This is because MacOS `AppKit` based applications (`NSApplication` or `NSWindow`) are forbidden to run as root.

See
* https://forums.developer.apple.com/forums/thread/702595
* https://lists.apple.com/archives/Cocoa-dev/2010/Jan/msg01418.html


I don't really know what you are trying to achieve but you can bypass this limitation running a setuid launcher that call your program.

CAREFUL though about any security issue!

**Comment by PBK-B** [comment]
@renard Thank you. I think I probably understand.
