### ISSUE TITLE
Use templated icons for the menu bar in macOS

### ISSUE THREAD

**Issue by stoggi** [getlantern/systray#45]
Since Yosemite (10.10+), the menubar supports templated images, so that macOS can automatically change the highlight for dark/light themed menu bars.

<img width="190" alt="menubar-light" src="https://user-images.githubusercontent.com/5227285/38526984-aaff28a0-3cac-11e8-8712-45be2d110f0b.png">
<img width="190" alt="menubar-dark" src="https://user-images.githubusercontent.com/5227285/38526985-ab30d378-3cac-11e8-95c3-b62cfe71a8ed.png">

Apple recommends using a Template Icon for the menu bar extras:
> **Use a template image to represent your menu bar extra.** A template image discards color information and uses a mask to produce the appearance you see onscreen. Template images automatically adapt to the user’s appearance settings, so they look good on both dark and light menu bars, and when your menu bar extra is selected.

https://developer.apple.com/macos/human-interface-guidelines/extensions/menu-bar-extras

**Comment by stoggi** [comment]
Note, that this will mean existing macOS systray users with colourful menu bar icons will be converted to monochrome templates as Apple suggest.

Not sure how to keep the API the same for all architectures while still letting the user specify template images.

One thought is perhaps checking the image to see if it's already monochrome, and only in that case make it a template. Depends on how people are using the icons I guess.

**Comment by joesis** [comment]
Yeah we have to hold off this as it's quite possible a colorful icon being used across platforms.

**Comment by flowchartsman** [comment]
I would add a SetTemplateIcon() (or something) call. This could be used in addition to, or in place of the SetIcon() call.
If both are used, the icon made with SetTemplateIcon will be used on OSX and the icon made with SetIcon will be used elsewhere.  If only SetTemplaceIcon() is called, then the dark version of the icon will be used on non-osx systems.

**Comment by joesis** [comment]
Reopening as https://github.com/getlantern/systray/pull/46 is reverted.

Another option would be to add a helper method like `UseTemplateIconOnDarwin`, so if it's called, `SetIcon` always converts the icon to a monochrome template on macOS. How do you think @stoggi @flowchartsman?

**Comment by flowchartsman** [comment]
Personally, I don't like that method name, tbh. IMO, if you're going to maintain the API, another method call like the one I mention above would be the way to go. This would allow you to selectively use different icons on OSX versus others. I would avoid changing the behavior of `SetIcon`, unless templated icons are not optional.  This would force users to comply to avoid their app looking weird.  If templated icons are *not* optional, I would do as little as possible to make them compliant (like cheaply converting to monochrome), which would also serve to make the user spend time on decent templated icons.

**Comment by flowchartsman** [comment]
My PR above adds this method along with example usage and a PDF example icon based on a [free vector image](https://openclipart.org/detail/174693/celtic-sword-silhouette-by-rones)
<img width="126" alt="screen shot 2018-07-24 at 5 03 32 pm" src="https://user-images.githubusercontent.com/926884/43166075-96a93184-8f63-11e8-81aa-7e159b795066.png">
<img width="121" alt="screen shot 2018-07-24 at 5 03 46 pm" src="https://user-images.githubusercontent.com/926884/43166076-9806a610-8f63-11e8-8b95-e34fac93d156.png">

**Comment by joesis** [comment]
No I don't think it's a good name either. My point is to treat whether to use template icon as a configuration instead of application logic. One benefit of using the helper method is that the developer can switch to template icon with a single line of code rather than having to add special handling for Darwin everywhere (as the changed example code in the PR demonstrated). An application would highly likely use same set of icons (or variants with pattern) on all platforms. 

Here's an example to use different sets of icons on different OS, which could be simpler than using `SetTemplateIcon`.

```
func initSystray() {
  var iconAssets map[string][]byte
  switch runtime.GOOS {
    case "darwin":
      systray.UseTemplateIconOnDarwin() // <- just add this
      iconAssets = loadIcons(".../icons/darwin")
    case "windows":
      iconAssets = loadIcons(".../icons/windows")
    ...
  }
  // same logic on all platforms.
}
```

It also requires less code to implement. 

One thing the helper can't do is to switch back and forth between using template icon or not, which I don't expect to happen in reality.

**Comment by oxtoacart** [comment]
@flowchartsman @stoggi @joesis I created a new PR based on the work from @flowchartsman but with a slightly different API. The `SetTemplateIcon` method takes a template icon and a regular icon so that it works on all platforms, using the template icon on macOS and falling back to the regular icon for other platforms.

**Comment by oxtoacart** [comment]
Fix is merged

**Comment by myleshorton** [comment]
Nice @oxtoacart!!

**Comment by flowchartsman** [comment]
Finally coming back to this. Great to see!
